version: '3'

services:
    db:
        image: postgres
        ports:
            - '5432'
        environment:
          - POSTGRES_DB=notes
          - POSTGRES_USER=dbadmin
          - POSTGRES_PASSWORD=password9876
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/notes
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - db:db
