# Generated by Django 3.0.6 on 2020-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_color', models.CharField(max_length=10)),
                ('text_bg', models.CharField(max_length=10)),
                ('text_style', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='note',
            name='date_added',
            field=models.DateField(default=None),
        ),
    ]
