# Generated by Django 3.0.6 on 2020-06-02 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200527_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
