# Generated by Django 3.0.6 on 2020-06-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_user'),
        ('note', '0003_auto_20200602_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteCss',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
